### ISSUE TITLE
Add support for CellReg analysis package

### ISSUE THREAD

**Issue by kabilar** [datajoint/element-calcium-imaging#14]
[CellReg](https://github.com/zivlab/CellReg)

**Comment by kabilar** [comment]
Not currently a priority.  Will considering adding upon user request.

**Comment by trose-neuro** [comment]
Would be great! Longitudinal matching are a challenge and CellReg is still the most complete package. Incorporating a cross-session ID for matching ROIs would be a first step.

**Comment by kabilar** [comment]
Thanks @trose-neuro.  Would love to learn more about your requirements and current pipeline.  Please schedule a meeting [here](https://meetings.hubspot.com/kabilar) so that we can discuss in further detail.
