### ISSUE TITLE
Add specificity in `scan.py/activate` docstring regarding `linking_module`

### ISSUE THREAD

**Issue by CBroz1** [datajoint/element-calcium-imaging#51]
Per 12/28/21 discussion, [activate docstring](https://github.com/datajoint/element-calcium-imaging/blob/main/element_calcium_imaging/scan.py#L23) should state:
"Required dependencies should be defined in the linking module"

**Comment by CBroz1** [comment]
@kabilar volunteered to tackle this, feel free to transfer to me.

**Comment by kabilar** [comment]
Completed
